/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface C4Button {
    }
    interface C4Page {
    }
}
declare global {
    interface HTMLC4ButtonElement extends Components.C4Button, HTMLStencilElement {
    }
    var HTMLC4ButtonElement: {
        prototype: HTMLC4ButtonElement;
        new (): HTMLC4ButtonElement;
    };
    interface HTMLC4PageElement extends Components.C4Page, HTMLStencilElement {
    }
    var HTMLC4PageElement: {
        prototype: HTMLC4PageElement;
        new (): HTMLC4PageElement;
    };
    interface HTMLElementTagNameMap {
        "c4-button": HTMLC4ButtonElement;
        "c4-page": HTMLC4PageElement;
    }
}
declare namespace LocalJSX {
    interface C4Button {
    }
    interface C4Page {
    }
    interface IntrinsicElements {
        "c4-button": C4Button;
        "c4-page": C4Page;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "c4-button": LocalJSX.C4Button & JSXBase.HTMLAttributes<HTMLC4ButtonElement>;
            "c4-page": LocalJSX.C4Page & JSXBase.HTMLAttributes<HTMLC4PageElement>;
        }
    }
}
